### ISSUE TITLE
docs about test.

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog/releaser-tools#14]
`TEST_CONVENTIONAL_GITHUB_RELEASER_TOKEN` is hashed by travis.

**Comment by stevemao** [comment]
https://github.com/conventional-changelog/conventional-github-releaser/pull/13#issuecomment-207433169 Thanks @thiagofelix for bringing this up

**Comment by hbetts** [comment]
Not sure if this is related, but how do I run `npm test` locally?

I get `OAuth2 authentication requires a token or key & secret to be set`. What token is it talking about?

Can the tests run offline (so I don't need to have internet access, or risk breaking something on GitHub.

**Comment by stevemao** [comment]
> Can the tests run offline (so I don't need to have internet access, or risk breaking something on GitHub.

No, this is actually not unit test.

**Comment by stevemao** [comment]
@hbetts But if you want to break the tests down into unit and e2e, by all means :)

**Comment by hutson** [comment]
Closing in favor of #17
