### ISSUE TITLE
Upgrade to meow ^4.0.0 breaks commands using the aliases

### ISSUE THREAD

**Issue by carlosvillademor** [conventional-changelog/releaser-tools#63]
Hi there,

when upgrading to meow ^4.0.0 on commit 8f120c99753bd6002e0788b5c71e63864719d6a5, the usage of the aliases on conventional-github-releaseer got broken. We have to use --token instead of -t, or --config instead of -n. 

The release notes of https://github.com/sindresorhus/meow/releases warn on the way minimist options need to be passed for version ^4.0.0.

I have created https://github.com/conventional-changelog/releaser-tools/pull/62 that solves the issue. On top of it, the second commit adds the types of the flags as recommended in meow's README. I haven't created test because src/cli.js is explicitly excluded from them.

By the way @hbetts, out of interest, why is that you mention using `yarn` in the contributing if you are using package-lock.json? I have used `npm` because of the existence of package-lock.json. The links to the GitHub repo for issues and PRs read `GitLab`, as another small thing to correct in the CONTRIBUTING.md

The tests initially did not run, because I'm in GMT+2 and the line `chunk.committerDate = dateFormat(chunk.committerDate, 'yyyy-mm-dd', true)` in the transform.js, for both GitHub and GitLab, the 8th of June at 00:00 gets transformed to 7th June at 22:00 I guess?

Please let me know any feedback.

**Comment by hbetts** [comment]
> I have created #62 that solves the issue.

Thank you @carlosvillademor for submitting a pull request to fix the broken CLI tool.

> By the way @hbetts, out of interest, why is that you mention using yarn in the contributing if you are using package-lock.json?

That would be because I originally refactored this mono-repository using Yarn, only to switch to `npm` when I couldn't get `yarn` to work with Lerna. I need to submit a change to the `CONTRIBUTING.md` file to fix the documentation.

> in the transform.js, for both GitHub and GitLab, the 8th of June at 00:00 gets transformed to 7th June at 22:00 I guess?

Looks like we need to update the unit test so that it uses the same date object, and then do the same UTC conversion.

**Comment by hbetts** [comment]
@carlosvillademor I accepted your pull request and then added a commit to address the environment variable defaults we talked about.

Successfully published:
 - conventional-github-releaser@3.1.1
 - conventional-gitlab-releaser@3.1.1
