### ISSUE TITLE
GitHubError: Not Found (404)

### ISSUE THREAD

**Issue by xcv58** [conventional-changelog/releaser-tools#67]
I tried in different repo, always get this error.

```sh
conventional-github-releaser
GitHubError: Not Found (404)
```

**Comment by hbetts** [comment]
@xcv58 as @E-Mell noted, GitHub returns a 404 error, regardless of whether the URL is incorrect, or a valid access token was not provided.

I've released version 3.1.0 of `conventional-github-releaser`, which now [contains a feature that allows you to turn on debug output](https://github.com/conventional-changelog/releaser-tools/tree/master/packages/conventional-github-releaser#debugging).

Please consider re-running your release with that `debug` flag set, and see what the release tool is sending to GitHub.

If you continue to encounter the 404 error, please feel free to re-open this issue.
