### ISSUE TITLE
v3.1.1 returns RequestError when posting release to GitHub

### ISSUE THREAD

**Issue by gmeans** [conventional-changelog/releaser-tools#80]
After updating to 3.1.1 I receive the following error when attempting to run the releaser:

```
RequestError: getaddrinfo ENOTFOUND api.github.comrepos api.github.comrepos:443
```

I assumed it was a string interpolation error missing the `/` at the end of the base URL. So I updated `CONVENTIONAL_GITHUB_URL` to be `https://api.github.com/`. 

After updating the env var, I receive a `GithubError`:

```
GitHubError: Validation Failed (422)
```

However it looks like the release does actually POST to Github.

This project was working fine, then we ran into issue #58 . This prompted us to try upgrading to the latest version which resulted in what I reported above.

Thanks!

**Comment by aaronjameslang** [comment]
+1

v1.3.0 works for now

**Comment by aaronjameslang** [comment]
`GitHubError: Validation Failed (422)` looks like it might happen if you try to release an already released version?

**Comment by hbetts** [comment]
The defaults for the `url` option were not set to their proper value in our code (In the case of GitHub, as @gmeans discovered, the trailing slash was missing).

I've released fixes for both release tools:

Successfully published:
 - conventional-github-releaser@3.1.2
 - conventional-gitlab-releaser@3.2.0

Going forward I'm going to just remove the defaults for the URL and rely on the underlying `got` libraries. The `got` libraries also include defaults, so our defaults are redundant.
